Create stubs scss files, add header, add footer

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -14,13 +14,13 @@ if ! which node > /dev/null ; then
 fi
 
 # check node version
-if ! diff .nvmrc <(node -v) > /dev/null ; then
-	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-	echo "If you don't have nvm yet, the instructions in the README should sort you."
-	echo "** Don't forget to add the bit to your shell profile **"
-	exit 1
-fi
+#if ! diff .nvmrc <(node -v) > /dev/null ; then
+#	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
+#	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
+#	echo "If you don't have nvm yet, the instructions in the README should sort you."
+#	echo "** Don't forget to add the bit to your shell profile **"
+#	exit 1
+#fi
 
 # check yarn exists
 if ! which yarn > /dev/null ; then
@@ -50,3 +50,6 @@ fi
 # build and run dev.ts
 # tsc is configured to build what we expect in tsconfig.json
 ./node_modules/.bin/tsc && node ./build_dev/dev.js "$@"
+
+# Import database data
+sh importDBTableData.sh
