CMDCT-4337 - ci/cd should still work you know

diff --git a/run b/run
--- a/run
+++ b/run
@@ -31,26 +31,6 @@ if ! which yarn > /dev/null ; then
 	exit 1
 fi
 
-if ! which op > /dev/null; then
-    echo "The MDCT team uses 1Password to store and retrieve development credentials. On macOS, you can install it with 'brew install --cask 1password-cli'"
-    exit 1
-fi
-
-if ! which docker > /dev/null ; then
-	echo "docker not found on the system. On macOS, you can install it with 'brew install docker'"
-	exit 1
-fi
-
-if ! which colima > /dev/null ; then
-	echo "colima not found on the system. On macOS, you can install it with 'brew install colima'"
-	exit 1
-fi
-
-if ! which localstack > /dev/null ; then
-	echo "localstack not found on the system. On macOS, you can install it with 'brew install localstack/tap/localstack-cli'"
-	exit 1
-fi
-
 # have to ensure that yarn install is up to date.
 # we use .yarn_install as a marker for the last time `yarn install` was run. Rerun the command when yarn.lock is updated
 if [ "yarn.lock" -nt ".yarn_install" ]; then
@@ -59,19 +39,45 @@ if [ "yarn.lock" -nt ".yarn_install" ]; then
 fi
 
 # Parse arguments
-LOCAL_ENV=false
+UPDATE_ENV=false
+LOCAL=false
 ARGS=()
 
 for arg in "$@"; do
     case $arg in
+        update-env)
+        UPDATE_ENV=true
+        ;;
         local)
-        LOCAL_ENV=true
+        LOCAL=true
         ;;
     esac
     ARGS+=("$arg")
 done
 
-if [ "$LOCAL_ENV" = true ]; then
+if [ "$UPDATE_ENV" = true ]; then
+    if ! which op > /dev/null; then
+        echo "The MDCT team uses 1Password to store and retrieve development credentials. On macOS, you can install it with 'brew install --cask 1password-cli'"
+        exit 1
+    fi
+fi
+
+if [ "$LOCAL" = true ]; then
+    if ! which docker > /dev/null ; then
+        echo "docker not found on the system. On macOS, you can install it with 'brew install docker'"
+        exit 1
+    fi
+
+    if ! which colima > /dev/null ; then
+        echo "colima not found on the system. On macOS, you can install it with 'brew install colima'"
+        exit 1
+    fi
+
+    if ! which localstack > /dev/null ; then
+        echo "localstack not found on the system. On macOS, you can install it with 'brew install localstack/tap/localstack-cli'"
+        exit 1
+    fi
+
     if ! colima status 2>&1 | grep -q "colima is running" ; then
         echo "colima installed but not running. We'll start it up for you now."
         colima start --cpu 4 --memory 10
@@ -79,7 +85,7 @@ if [ "$LOCAL_ENV" = true ]; then
 
     if ! localstack status | grep -q "running" ; then
         echo "localstack is installed but not running. We'll start it up for you now."
-        localstack start &
+        localstack start > /dev/null 2>&1 &
     fi
 fi
 
