modularizing the run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,7 +3,7 @@
 set -eu -o pipefail
 
 # this is the entrypoint for development. It wraps up compiling and calling run.ts
-# all arguments, changes, etc. should be found in src/run.ts
+# all arguments, changes, etc. should be found in cli/run.ts
 
 # this script checks for all the prereqs and then calls run.ts
 
@@ -17,13 +17,11 @@ if ! which node > /dev/null ; then
 fi
 
 # check node version
-#if ! diff .nvmrc <(node -v) > /dev/null ; then
-#	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-#	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-#	echo "If you don't have nvm yet, the instructions in the README should sort you."
-#	echo "** Don't forget to add the bit to your shell profile **"
-#	exit 1
-#fi
+if ! diff  <(cat .nvmrc | tr -d '\n') <(node -v | tr -d '\n') > /dev/null ; then
+	echo "node version does not match the version required in .nvmrc"
+	echo "If using nvm, run 'nvm use'"
+	exit 1
+fi
 
 # check yarn exists
 if ! which yarn > /dev/null ; then
@@ -89,6 +87,13 @@ if [ "$LOCAL" = true ]; then
     fi
 fi
 
-# build and run run.ts
-# tsc is configured to build what we expect in tsconfig.json
-./node_modules/.bin/tsc && node ./build_dev/src/run.js "${ARGS[@]-}"
+pushd cli
+yarn install --frozen-lockfile
+popd 
+
+# Ensure packages are up to date.
+yarn install --frozen-lockfile
+
+# build the CLI and run it from cli/dist
+yarn --cwd cli tsc -p tsconfig.json
+node ./cli/dist/run.js "${ARGS[@]-}"
